# Site Settings
author: "@ghaiklor"
exclude: [vendor]
lang: en
remote_theme: yous/whiteglass

# SEO Settings
title: Type Challenges Solutions
description: This project is aimed at helping you better understand how the type system works, writing your own utilities, or just having fun with the challenges.

# Plugin Settings
plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Social Media Settings
twitter_username: "@ghaiklor"
twitter_image: "favicon.png"

# Google Analytics Settings
google_analytics: G-VY8KWPMEYK

# Comments Settings
comments: true
